package c196.mheino.myscheduler.Entity;


import androidx.room.Entity;
import androidx.room.Ignore;
import androidx.room.PrimaryKey;

/** This class will model data for the course instructor. This class will be
 *  used to model the data that will compose the database table that will hold
 *  data about the course instructor. The primary key will be autogenerated by
 *  the database.
 *
 * @author  Matthew Heino
 */

@Entity(tableName = "course_instructor_table")
public class CourseInstructorEntity {

    @PrimaryKey(autoGenerate = true)
    private int id;


    private String firstName;
    private String lastName;
    private String phoneNumber;
    private String email;


    /** The Room constructor for the course instructor.  This constructor will be used to
     *  for the object for the data that is returned from the database.  The
     *  ID has been omitted since this wil be be created by the database. Note:
     *  A setter for the ID has been created below. (Will be used for the Room)
     *
     * @param firstName
     * @param lastName
     * @param phoneNumber
     * @param email
     */
    public CourseInstructorEntity(String firstName, String lastName,
                                  String phoneNumber, String email)
    {
        this.firstName = firstName;
        this.lastName = lastName;
        this.phoneNumber = phoneNumber;
        this.email = email;
    }

    /** The Room constructor for the course instructor.  This constructor will be used to
     *  for the object for the data that is returned from the database.
     *
     * @param firstName
     * @param lastName
     * @param phoneNumber
     * @param email
     *
     */
    @Ignore
    public CourseInstructorEntity(int id, String firstName, String lastName
            , String phoneNumber, String email)
    {

        this.id = id;
        this.firstName = firstName;
        this.lastName = lastName;
        this.phoneNumber = phoneNumber;
        this.email = email;
    }

    @Ignore
    public CourseInstructorEntity(){
        this.id = -1;
        this.firstName = "";
        this.lastName ="";
        this.phoneNumber ="";
        this.email = "";

    }

    /** Method to get the ID of the course instructor.
     *
     * @return
     *
     */
    public int getId() { return id; }

    /** Method to set the ID of the course instructor
     *
     * @param id
     *
     */
    public void setId(int id) { this.id = id; }

    /** Method to get the first name of the instructor.
     *
     * @return
     *
     */
    public String getFirstName() {
        return firstName;
    }

    /** Method to set the first name of the course instructor
     *
     * @param firstName
     *
     */
    public void setFirstName(String firstName) { this.firstName = firstName; }

    /** Method to get the last name of the instructor.
     *
     * @return
     *
     */
    public String getLastName() { return lastName; }

    /** Method to set the last name of the course instructor.
     *
     * @param lastName
     *
     */
    public void setLastName(String lastName) { this.lastName = lastName; }

    /** Method to get the course instructor's phone number
     *
     * @return
     *
     */
    public String getPhoneNumber() {  return phoneNumber; }

    /** Method to set the phone number of the instructor.
     *
     * @param phoneNumber
     *
     */
    public void setPhoneNumber(String phoneNumber) { this.phoneNumber = phoneNumber; }

    /** Method to get the email of the course instructor.
     *
     * @return
     *
     */
    public String getEmail() { return email;  }

    /** Method to set the email of the course instructor.
     *
     * @param email
     *
     */
    public void setEmail(String email) { this.email = email; }

    /** Method that will return the string containing the first name and the
     *  last name of the course instructor.
     *
     * @return
     *
     */
    @Override
    public String toString() {

        String fullname = firstName + " " + lastName;
        return fullname;
    }

} // end class
