package c196.mheino.myscheduler.Entity;

import androidx.room.Entity;
import androidx.room.Ignore;
import androidx.room.PrimaryKey;

/** This class will model data for the term. This class will be used to model
 *  the data that will compose the database table that will hld data about the
 *  term. The primary key will be autogenerated by the database.
 *
 * @author  Matthew Heino
 */
@Entity(tableName = "term_table")
public class TermEntity {

    @PrimaryKey(autoGenerate = true)
    private int termID;                 // Term ID and the primary key for the table

    private String termTitle;           // Term Title
    private String startDate;           // The start date of the Term.
    private String endDate;             // End of the term.


    /** The Room constructor for the Term.  This constructor will be used to
     *  for the object for the data that is returned from the database.  The
     *  ID has been omitted since this wil be be created by the database. Note:
     *  A setter for the ID has been created below. (Will be used for the Room)
     *
     * @param termTitle
     * @param startDate
     * @param endDate
     */
    public TermEntity(String termTitle, String startDate, String endDate) {

        this.termTitle = termTitle;
        this.startDate = startDate;
        this.endDate = endDate;
    }

    /** Construct that will be used to test the app without using a Room
     *  database. THis method is used to to test the different views without
     *  the use of a Room database.  This method includes the Term ID that was
     *  omitted in the constructor for the Room version of the constructor.
     *
     * @param termID
     * @param title
     * @param startDate
     * @param endDate
     */
    @Ignore
    public TermEntity(int termID, String title, String startDate, String endDate) {

        this.termID = termID;
        this.termTitle = title;
        this.startDate = startDate;
        this.endDate = endDate;
    }

    /** Method to return the TermId.  This method will return the Term's ID.
     *  This method will return the integer value ID.
     *
     * @return
     */
    public int getTermID() {
        return termID;
    }

    /** Method to set the Term's ID. This method will set the Term's ID.  This
     *  method is used for setting the ID for use with the Room.
     *
     * @param termID
     *
     */
    public void setTermID(int termID) {
        this.termID = termID;
    }

    /** Method to return the Term Title.  This method will return the Term's
     * title. This method will return the String value title.
     *
     * @return
     */
    public String getTermTitle() {
        return termTitle;
    }

    /** Method to set the Term's Title. This method will set the Term's title.
     *
     * @param termTitle
     *
     */
    public void setTermTitle(String termTitle) { this.termTitle = termTitle; }

    /** Method to return the Term start date.  This method will return the Term's
     * start date. This method will return the String value of the start date.
     *
     * @return
     */
    public String getStartDate() {
        return startDate;
    }

    /** Method to set the Term's start date. This method will set the Term's
     *  start date.
     *
     * @param startDate
     *
     */
    public void setStartDate(String startDate) {
        this.startDate = startDate;
    }

    /** Method to return the Term end date.  This method will return the Term's
     * end date. This method will return the String value of the end date.
     *
     * @return
     */
    public String getEndDate() {
        return endDate;
    }

    /** Method to set the Term's end date. This method will set the Term's
     *  end date.
     *
     * @param endDate
     *
     */
    public void setEndDate(String endDate) {
        this.endDate = endDate;
    }

    /** The to string method
     *   **may need to be changed for use with the spinner************************************
     *
     * @return
     */
    @Override
    public String toString() {
        return "TermEntity{" +
                "termID=" + termID +
                ", termTitle='" + termTitle + '\'' +
                ", startDate='" + startDate + '\'' +
                ", endDate='" + endDate + '\'' +
                '}';
    }

} // end class
